In [1]:
import numpy as np

In [2]:
arr=[[1,2],[3,4]]
print arr

[[1, 2], [3, 4]]


In [3]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [9]:
#print arr
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [10]:
#print np.ones((2,2))
torch.ones((2,2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [12]:
#print np.random.rand(2,2)
print torch.rand(2,2)


 0.6241  0.0737
 0.5520  0.2666
[torch.FloatTensor of size 2x2]



In [15]:
np.random.seed(0)
print np.random.rand(2,2)
#print np.random.rand(2,2)

[[ 0.5488135   0.71518937]
 [ 0.60276338  0.54488318]]


In [16]:
np.random.seed(0)
print np.random.rand(2,2)
#print np.random.rand(2,2)

[[ 0.5488135   0.71518937]
 [ 0.60276338  0.54488318]]


In [17]:
torch.manual_seed(0)
torch.rand(2,2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [23]:
torch.manual_seed(0)
torch.rand(2,2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [20]:
#if cuda is available
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [33]:
np_arr=np.ones((2,2))
print np_arr
print type(np_arr)

[[ 1.  1.]
 [ 1.  1.]]
<type 'numpy.ndarray'>


In [34]:
#numpy to torch
tor_tensor=torch.from_numpy(np_arr)
print tor_tensor


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [40]:
np_arr_new=np.ones((2,2),dtype=np.int8)
print np_arr
print type(np_arr)
tor_tensor_new=torch.from_numpy(np_arr_new)

[[ 1.  1.]
 [ 1.  1.]]
<type 'numpy.ndarray'>


RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

In [41]:
np_arr_new=np.ones((2,2),dtype=np.uint8)
print np_arr
print type(np_arr)

[[ 1.  1.]
 [ 1.  1.]]
<type 'numpy.ndarray'>


In [42]:
tor_tensor_new=torch.from_numpy(np_arr_new)

In [44]:
#torch to numpy
tor_to_np = tor_tensor_new.numpy()
print tor_to_np
print type(tor_to_np)

[[1 1]
 [1 1]]
<type 'numpy.ndarray'>


# Tensor Operations

In [46]:
a=torch.ones(2,2)
print a
print a.size()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

torch.Size([2, 2])


In [53]:
a.view(4).size()

torch.Size([4])

In [57]:
#normal addition
a=torch.ones(2,2)
b=torch.ones(2,2)
c=a+b
print c
c1=torch.add(a,b)
print c1


 2  2
 2  2
[torch.FloatTensor of size 2x2]


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [63]:
# inplace addition  '_' is important in inplace same for subtraction also
c.add_(b)
print c


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [60]:
#Multiplication
a*c


 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [64]:
a.mul_(c)
print a
c=torch.mul(a,b)
print c


 2  2
 2  2
[torch.FloatTensor of size 2x2]


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [75]:
a=torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print a.size()
a.mean(dim=1)

torch.Size([2, 10])



 5.5000
 5.5000
[torch.FloatTensor of size 2]

# Variable and Autograd

In [2]:
import torch
from torch.autograd import Variable

In [3]:
a=Variable(torch.ones(2,2), requires_grad=True)

In [4]:
print a
b=Variable(torch.ones(2,2), requires_grad=True)
c=torch.add(b,a)
print c

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

Variable containing:
 2  2
 2  2
[torch.FloatTensor of size 2x2]



#### consider the eq y=5(x+1)**2
#### also o=1/2 summation y

In [22]:
x=Variable(torch.ones(2), requires_grad=True)
x

Variable containing:
 1
 1
[torch.FloatTensor of size 2]

In [23]:
y = 5*(x+1)**2
print y

Variable containing:
 20
 20
[torch.FloatTensor of size 2]



In [24]:
print y
o=(torch.sum(y))/2
print o

Variable containing:
 20
 20
[torch.FloatTensor of size 2]

Variable containing:
 20
[torch.FloatTensor of size 1]



In [12]:
o.backward()

In [13]:
x.grad

Variable containing:
 10
 10
[torch.FloatTensor of size 2]

In [25]:
print o.backward(torch.FloatTensor([2.0,2.0]))
x.grad

None


Variable containing:
 20
 20
[torch.FloatTensor of size 2]